- redhat_subscription: state=absent
- redhat_subscription: state=present username={{rhnuser}} password={{rhnpassword}}
  ignore_errors: yes
#- name: Retrieve the OpenShift Pool ID
#  command: subscription-manager list --available --matches="Employee SKU" --pool-only
#  register: openshift_pool_id
# # ignore_errors: yes
#  changed_when: False

- name: Attach to OpenShift Pool
  ignore_errors: yes
#  command: subscription-manager attach --pool={{ openshift_pool_id.stdout_lines[1] }}
  command: subscription-manager attach --pool={{ pool }}
- name: disable
  command: subscription-manager repos --disable="*"
- name: enable
  command:  subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-3.2-rpms"
