- name: Set configuration file
  template:
    src: hosts.j2
    dest: /etc/ansible/hosts
  tags: ose
- name: Set customer configuration file
  template:
    src: prepare.hosts.j2
    dest: /etc/ansible/prepare.hosts
  tags: ose
